### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by TheNetStriker** [KintaroCo/KintaroSnes#3]
I've just tried this version of the script, but it doesn't seam to work. I'm getting this error:

```
/opt/kintaro/pcb.py:38: RuntimeWarning: A physical pull up resistor is fitted on this channel!
  GPIO.setup(pcb_components["RESET"], GPIO.IN, pull_up_down=GPIO.PUD_UP) #set pin as input and switch on internal pull up resistor
Traceback (most recent call last):
  File "/opt/kintaro/pcb.py", line 129, in <module>
    GPIO.add_event_detect(pcb_components["CHECK_PCB"],GPIO.RISING,callback=PCB_Pull)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
```
The error goes away if I uncomment the line GPIO.cleanup(). But I'am now using the script out of the official retropie image. That one is working.

**Comment by MichaelKirsch** [comment]
When you uncomment the line then the code wont reset your GPIOs to the default state. This can be problematic when you want to implement own scripts. Do you run scripts that use the same GPIO pins ? For further discussion can you please open an issue here: https://github.com/MichaelKirsch/KintaroSnes as that is the one that is developed by me
